replicaCount: 1

image:
  repository: 629068384298.dkr.ecr.us-east-1.amazonaws.com/go-web-app
  tag: "33489139032"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  path: /
  pathType: Prefix
