replicaCount: 2

blue:
  image:
    repository: 629068384298.dkr.ecr.us-east-1.amazonaws.com/go-web-app
    tag: "33490813410"

green:
  image:
    repository: 629068384298.dkr.ecr.us-east-1.amazonaws.com/go-web-app
    tag: "33492119384"

image:
  pullPolicy: IfNotPresent

activeVersion: blue

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  path: /
  pathType: Prefix
